/*******************************************************************************
*      Filename: file_utils.c
*        Author: Maxwell Goldberg
* Last Modified: 03.17.17
*   Description: Provides utilities for validating plain/ciphertext and key text
*                files.
*******************************************************************************/

#include "file_utils.h"

/*******************************************************************************
*      Function: validateFileReg()
*   Description: Determines whether or not a file is a regular file.
*    Parameters: struct stat *buf - A pointer to the file's filled in stat 
*                                   struct.
* Preconditions: None.
*       Returns: 0 if the file is a regular file, -1 otherwise.
*******************************************************************************/

int validateFileReg(struct stat *buf) {
    /* Test the struct pointer */ 
    if (!buf) {
        fprintf(stderr, "getFileSize: NULL FILE ptr arg\n");
        return -1;
    }
    /* Use the POSIX S_ISREG macro to determine file regularity */
    if (!S_ISREG(buf->st_mode)) {
        fprintf(stderr, "getFileSize: Not a regular file\n");
        return -1;
    }
    return 0;
}

/*******************************************************************************
*      Function: validateFileChars()
*   Description: Validates the characters in a file. Files must contain only
*                upper case letters, spaces, and at most one POSIX line feed
*                at the end of the file. Determines the number of non-line feed
*                characters in the file.
*    Parameters: FILE *fptr - The file pointer.
* Preconditions: None.
*       Returns: -1 if invalid characters are present. A nonnegative integer
*                representing the number of characters, otherwise.
*******************************************************************************/

int validateFileChars(FILE *fptr) {
    int c;
    int count = 0;
    int newlineFound = 0;
  
    /* Test the file pointer */
    if (!fptr) {
        fprintf(stderr, "validateFileChars: NULL FILE ptr arg\n");
        return -1;
    }
    /* Increment the pointer until we hit EOF, storing each char in c */
    while ((c = fgetc(fptr)) != EOF) {
        /* If we've found a newline before EOF, the newline is invalid. */
        if (newlineFound) {
            fprintf(stderr, "Error: Input contains bad characters\n");
            return -1;
        } 
        
        if (c == '\n') {
            newlineFound = 1;
        } else {
            count++;
        }
        /* If the char isn't valid, return immediately */ 
        if (!isupper(c) && c != ' ' && c != '\n') {
            fprintf(stderr, "Error: Input contains bad characters\n");
            return -1;
        }
    } 
    /* Check the final error value generated by fgetc to make sure we didn't
     * attempt to read past the maximum filestream offset */
    if (ferror(fptr) != 0) {
        perror("validateFileChars: fgetc");
        return -1;
    }
    /* Rewind the file pointer to the begining of the file */
    rewind(fptr);

    return count;
}

/*******************************************************************************
*      Function: validateFile()
*   Description: Validates a single file.
*    Parameters: FILE *fptr - A pointer to the file.
* Preconditions: None.
*       Returns: The number of non-line feed chars in the file on success, -1
*                otherwise.
*******************************************************************************/

int validateFile(FILE *fptr) {
    struct stat buf = {0};
    int fd, size, status;
    /* Test the file pointer */
    if (!fptr) {
        fprintf(stderr, "validateFile: NULL ptr argument\n");
        return -1;
    }
    /* Get the file descriptor */
    fd = fileno(fptr);
    if (fd == -1) {
        perror("getFileSize: fileno");
        return -1;
    }
    /* Inform the stat struct */ 
    status = fstat(fd, &buf);
    if (status == -1) {
        perror("getFileSize: fstat");
        return -1;
    }
    /* Test file regularity */
    status = validateFileReg(&buf);
    if (size == -1) {
        return -1;
    }
    /* Validate file characters */ 
    size = validateFileChars(fptr);
    if (size == -1) {
        return -1;
    }

    return size;
}

/*******************************************************************************
*      Function: validateFiles()
*   Description: Validates text and key files, storing the number of characters
*                to be processed in each file in integers passed by pointer.
*    Parameters: FILE *ptextPtr - The text file pointer.
*                FILE *keyPtr - The key file pointer.
*                int *ptextSize - The text file size pointer.
*                int *keySize - The key file size pointer.
* Preconditions: None.
*       Returns: 0 on success, -1 otherwise.
*******************************************************************************/

int validateFiles(FILE *ptextPtr, FILE *keyPtr, int *ptextSize, int *keySize) {
    int status;
 
    /* Validate the text file */ 
    *ptextSize = validateFile(ptextPtr);
    if (*ptextSize == -1) {
        return -1;
    }
    /* Validate the key file */
    *keySize = validateFile(keyPtr);
    if (*keySize == -1) {
        return -1;
    }
    /* Ensure the key file has at least as many chars as the text file */
    if (*ptextSize > *keySize) {
        fprintf(stderr, "Error: key is too short\n");
        return -1;
    }

    return 0;
}
